# Generated by Django 4.1.7 on 2023-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("water_level", models.FloatField()),
                ("wifi_status", models.BooleanField()),
                ("spray_status", models.IntegerField()),
            ],
        ),
    ]
